import {
    ABank,
    AdvCash,
    AED,
    AirTM,
    AkBarsBank,
    AlfaBank,
    Alipay,
    AMD,
    ARB,
    AZN,
    BankTransfer,
    BCSBank,
    BINANCE,
    BINGX,
    BITGET,
    BITPAPA,
    BNB,
    BTC,
    BYBIT,
    BYN,
    CNY,
    COMMEX,
    DAI,
    DOGE,
    ETH,
    EUR,
    EXMO,
    FDUSD,
    GATEIO,
    Gazprombank,
    GBP,
    GEL,
    HKD,
    HomeCreditBank,
    HT,
    HUOBI,
    INR,
    KCS,
    KGS,
    KRAKEN,
    KUCOIN,
    KZT,
    LTC,
    MANTLE,
    MEXC,
    Monobank,
    MTSBank,
    OKX,
    Oldubil,
    OtkritieBank,
    OTP,
    Ozon,
    PAYEER,
    Paysend,
    Paytm,
    PerfectMoney,
    PostBank,
    PriorBank,
    PrivatBank,
    QiWi,
    RaiffeisenBank,
    RenaissanceCreditBank,
    Revolut,
    Rocketbank,
    Rosbank,
    Rosselkhozbank,
    RSD,
    RUB,
    RussianStandardBank,
    Sberbank,
    SBP,
    SepaInstant,
    Skrill,
    SOL,
    SWIFT,
    Tinkoff,
    TON,
    TRX,
    TRY,
    TurkishBank,
    TUSD,
    UAH,
    Unibank,
    UniCredit,
    UnionPay,
    Upi,
    UralsibBank,
    USD,
    USDC,
    USDD,
    USDT,
    UZS,
    VTBBANK,
    Wechat,
    Wise,
    XMR,
    XRP,
    YooMoney,
    MIR,
    Sovkombank,
    MATIC,
    LUNC,
    FIL,
    WAX,
} from "../../components/Icons"


export const NAME_PAGE = {
    P2P: 'P2P',
    SPOT: 'Spot',
    HELP: 'Help',
    BLACK_LIST: 'BlackList',
    SETTINGS: 'Settings',
    SUBSCRIPTION: 'Subscription',
    ARBITRAGE: 'Arbitrage',
    PERSONAL_AREA: 'PersonalArea',
    LOGIN: 'Login',
    REGISTRATION: 'Registration',
    SPREAD: 'Spread',
    P2PSPREAD: 'P2Pspread',
    CALCULATOR: 'Calculator',
    CALCULATOR_SPREAD: 'Calculator spread',
    CALCULATOR_PERCENT: 'Calculator percent',
}

export const BUTTON_TYPE = {
    PRIMARY: 'primary',
    SECONDARY: 'secondary',
    TEXT: 'text'
}

export const TABLE_SELL_SIZE = {
    XS: 'xs',
    S: 's',
    M: 'm',
    L: 'l',
    XL: 'xl',
}

export const BANK = {
    "Raiffaisen Bank": RaiffeisenBank,
    "Raiffaizen": RaiffeisenBank,
    "Raiffeisen (AT)": RaiffeisenBank,
    "Raiffeisen (IT)": RaiffeisenBank,
    "Raiffeisen Bank Aval": RaiffeisenBank,
    "Raiffeisenbank": RaiffeisenBank,
    "Sberbank": Sberbank,
    "HomeCreditBank": HomeCreditBank,
    "Home Credit": HomeCreditBank,
    "Home Credit Bank (Russia)": HomeCreditBank,
    "Home Credit Bank(Russia)": HomeCreditBank,
    "Home Credit Kazakhstan": HomeCreditBank,
    "Tinkoff": Tinkoff,
    "Tinkoff Bank": Tinkoff,
    "tinkoff": Tinkoff,
    "BCS Bank": BCSBank,
    "BCS bank": BCSBank,
    "AirTM": AirTM,
    "Advcash": AdvCash,
    "AdvCash": AdvCash,
    "ADVCash": AdvCash,
    "AirTm": AirTM,
    "Ak Bars Bank": AkBarsBank,
    "Alfa Bank": AlfaBank,
    "Alfa-bank": AlfaBank,
    "Gazprombank": Gazprombank,
    "MTS-Bank": MTSBank,
    "MTS Bank": MTSBank,
    "OTP": OTP,
    "OTP BANK": OTP,
    "OTP Bank": OTP,
    "Oldubil": Oldubil,
    "Otkritie Bank": OtkritieBank,
    "Ozon": Ozon,
    "OZON Bank": Ozon,
    "PAYEER": PAYEER,
    "Payeer": PAYEER,
    "Paysend": Paysend,
    "Paysend.com": Paysend,
    "Perfect Money": PerfectMoney,
    "Post Bank": PostBank,
    "Postbank": PostBank,
    "PriorBank": PriorBank,
    "Privat Bank": PrivatBank,
    "Privat Bank (Universal Card)": PrivatBank,
    "PrivatBank": PrivatBank,
    "QiWi": QiWi,
    "QIWI": QiWi,
    "Renaissance Credit Bank": RenaissanceCreditBank,
    "Rocketbank": Rocketbank,
    "Rosbank": Rosbank,
    "Rosselkhozbank": Rosselkhozbank,
    "Russian Standard Bank": RussianStandardBank,
    "Russian standard bank": RussianStandardBank,
    "SBP - Fast Bank Transfer": SBP,
    "SBP - Sistema bystryh platezhej": SBP,
    "SBP": SBP,
    "СБП": SBP,
    "SWIFT": SWIFT,
    "SWIFT international remittance": SWIFT,
    "Skrill": Skrill,
    "Turkish Bank": TurkishBank,
    "UniCredit": UniCredit,
    "UniCredit Bank": UniCredit,
    "UniCredit Bank (IT)": UniCredit,
    "Unibank": Unibank,
    "UnionPay": UnionPay,
    "Uralsib Bank": UralsibBank,
    "VTB BANK": VTBBANK,
    "VTB Bank": VTBBANK,
    "Sovkombank": Sovkombank,
    "Sovcombank": Sovkombank,
    "SOVCOMBANK": Sovkombank,
    "Bank Tranfer (Cambodia)": BankTransfer,
    "Bank Transfer": BankTransfer,
    "Bank Transfer (Argentina)": BankTransfer,
    "Bank Transfer (Cambodia)": BankTransfer,
    "Bank Transfer (Costa Rica)": BankTransfer,
    "Bank Transfer (India)": BankTransfer,
    "Bank Transfer (Laos)": BankTransfer,
    "Bank Transfer (Middle East)": BankTransfer,
    "Bank Transfer (Romania)": BankTransfer,
    "Bank Transfer (Taiwan)": BankTransfer,
    "Bank Transfer (Turkey)": BankTransfer,
    "Bank Transfer (Vietnam)": BankTransfer,
    "Bank Transfer Peru": BankTransfer,
    "Bank transfer (Costa Rica)": BankTransfer,
    "Bank transfer (India)": BankTransfer,
    "bank transfer (costa rica)": BankTransfer,
    "bank transfer (argentina)": BankTransfer,
    "bank transfer (vietnam)": BankTransfer,
    "bank transfer (arab)": BankTransfer,
    "bank transfer (middle east)": BankTransfer,
    "bank transfer (turkey)": BankTransfer,
    "bank transfer (india)": BankTransfer,
    "bank transfer": BankTransfer,
    "Upi": Upi,
    "UPI": Upi,
    "revolut": Revolut,
    "Revolut": Revolut,
    "imps": Upi,
    "IMPS": Upi,
    "alipay": Alipay,
    "Alipay": Alipay,
    "AlipayHK": Alipay,
    "alipayhk": Alipay,
    "aliPay": Alipay,
    "wise": Wise,
    "Wise Instant": Wise,
    "Wise": Wise,
    "transfer wise": Wise,
    "Transfer Wise": Wise,
    "monobank": Monobank,
    "Monobank": Monobank,
    "Wechat": Wechat,
    "WeChat": Wechat,
    "wechat": Wechat,
    "paytm": Paytm,
    "PAYTM": Paytm,
    "Paytm": Paytm,
    "SEPA": SepaInstant,
    "SEPA (EU) Bank Transfer": SepaInstant,
    "SEPA(EU)Bank Transfer": SepaInstant,
    "SEPA (EU) Bank transfer": SepaInstant,
    "SEPA (EU) bank transfer": SepaInstant,
    "SEPA Instant": SepaInstant,
    "sepa(eu)bank transfer": SepaInstant,
    "sepa (eu) bank transfer": SepaInstant,
    "sepa": SepaInstant,
    "sepa instant": SepaInstant,
    "A-Bank": ABank,
    "a-bank": ABank,
    "YooMoney": YooMoney,
    "ЮMoney": YooMoney,
    "MIR": MIR,
}

export const STOCK = {
    "KUCOIN": "KUCOIN",
    "MEXC": "MEXC",
    "OKX": OKX,
    "HUOBI": HUOBI,
    "KRAKEN": KRAKEN,
    "BITGET": BITGET,
    "BYBIT": BYBIT,
    "EXMO": EXMO,
    "BINANCE": BINANCE,
    "COMMEX": COMMEX,
    "GATEIO": GATEIO,
    "BITPAPA": BITPAPA,
    "BINGX": BINGX,
}

export const CRYPTO = {
    "BTC": "BTC",
    "BTC (Bitcoin)": "BTC",
    "ETH": "ETH",
    "ETH (ERC20)": "ETH",
    "USDT": "USDT",
    "BNB": "BNB",
    "BSC (BEP20)": "BNB",
    "DAI": "DAI",
    "DOGE": "DOGE",
    "FDUSD": "FDUSD",
    "HT": "HT",
    "KCS": "KCS",
    "LTC": "LTC",
    "TRX": "TRX",
    "TRX (TRC20)": "TRX",
    "SOL": "SOL",
    "SOL (Solana)": "SOL",
    "TUSD": "TUSD",
    "USDC": "USDC",
    "USDD": "USDD",
    "XRP": "XRP",
    "XMR": "XMR",
    "TON": "TON",
    "ARBITRUM (Arbitrum One)": "ARB",
    "MANTLE (Mantle Network)": "MANTLE",
    "MATIC": "MATIC",
    "MATIC (Polygon)": "MATIC",
    "LUNC": "LUNC",
    "LUNC (Terra Classic)": "LUNC",
    "FIL": "FIL",
    "FIL (FIL)": "FIL",
    "WAXP": "WAX",
    "WAX (WAX)": "WAX",

}
export const LANGUAGE = {
    "RU": RUB,
    "ru": RUB,
    "RUB": RUB,
    "TRY": TRY,
    "UAH": UAH,
    "USD": USD,
    "UZS": UZS,
    "KZT": KZT,
    "GB": GBP,
    "GBP": GBP,
    "gb": GBP,
    "en": GBP,
    "EUR": EUR,
    "CNY": CNY,
    "BYN": BYN,
    "AMD": AMD,
    "AED": AED,
    "RSD": RSD,
    "AZN": AZN,
    "GEL": GEL,
    "HKD": HKD,
    "INR": INR,
    "KGS": KGS,
}


export const P2P_FAQ = [
    {
        title: 'Риски',
        description: 'Ненадежные мерчанты\nБыстрое изменение цены'
    },
    {
        title: 'Заголовок',
        description: 'Описание'
    },
    {
        title: 'А что такое P2P?',
        description: 'Большой большой секрет'
    }
]